# Fun Project 1 - Rand Terrorism Database

In [12]:
import pandas as pd
import numpy as np
import plotly
import plotly.plotly as py
import plotly.graph_objs as go
import matplotlib.pyplot as plt
plotly.tools.set_credentials_file(username='cneves4', api_key='YI7E2Dxy7g63cjKdD3Tk')

# Data Wrangling

In [37]:
#import rand dataset 
#source: RAND Database of Worldwide Terrorism Incidents
data = pd.read_excel('rand.xls')
data.head()

,Date,City,Country,Perpetrator,Weapon,Injuries,Fatalities,Description
0,1968-02-09,Buenos Aires,Argentina,Unknown,Firearms,0,0,ARGENTINA. The second floor of the U.S. embas...
1,1968-02-12,Santo Domingo,Dominican Republic,Unknown,Explosives,0,0,DOMINICAN REPUBLIC. A homemade bomb was found...
2,1968-02-13,Montevideo,Uruguay,Unknown,Fire or Firebomb,0,0,URUGUAY. A Molotov cocktail was thrown outsid...
3,1968-02-20,Santiago,Chile,Unknown,Explosives,0,0,CHILE. An explosion from a single stick of dy...
4,1968-02-21,"Washington, D.C.",United States,Unknown,Explosives,0,0,UNITED STATES. The Soviet embassy was bombed ...

In [38]:
data = data[['Date', 'City','Country', 'Perpetrator', 'Weapon', 'Injuries', 'Fatalities']]
data.head()

,Date,City,Country,Perpetrator,Weapon,Injuries,Fatalities
0,1968-02-09,Buenos Aires,Argentina,Unknown,Firearms,0,0
1,1968-02-12,Santo Domingo,Dominican Republic,Unknown,Explosives,0,0
2,1968-02-13,Montevideo,Uruguay,Unknown,Fire or Firebomb,0,0
3,1968-02-20,Santiago,Chile,Unknown,Explosives,0,0
4,1968-02-21,"Washington, D.C.",United States,Unknown,Explosives,0,0

# Plotting

1) # of Attacks in US Soil by Year

In [39]:
#separate dates
#test set
data['Year'] = data['Date'].apply(lambda x: x.strftime('%Y'))     
data['Month'] = data['Date'].apply(lambda x: x.strftime('%m'))     
data['Day'] = data['Date'].apply(lambda x: x.strftime('%d'))     
data.head()

,Date,City,Country,Perpetrator,Weapon,Injuries,Fatalities,Year,Month,Day
0,1968-02-09,Buenos Aires,Argentina,Unknown,Firearms,0,0,1968,02,09
1,1968-02-12,Santo Domingo,Dominican Republic,Unknown,Explosives,0,0,1968,02,12
2,1968-02-13,Montevideo,Uruguay,Unknown,Fire or Firebomb,0,0,1968,02,13
3,1968-02-20,Santiago,Chile,Unknown,Explosives,0,0,1968,02,20
4,1968-02-21,"Washington, D.C.",United States,Unknown,Explosives,0,0,1968,02,21

In [9]:
data_us = data[data['Country'] == 'United States']
data_us.head()

,Date,City,Country,Perpetrator,Weapon,Injuries,Fatalities,Year,Month,Day
4,1968-02-21,"Washington, D.C.",United States,Unknown,Explosives,0,0,1968,02,21
19,1968-03-19,Miami,United States,Anti-Castro Cubans,Explosives,0,0,1968,03,19
23,1968-04-22,New York City,United States,Anti-Castro Cubans,Explosives,0,0,1968,04,22
24,1968-04-22,New York City,United States,Anti-Castro Cubans,Explosives,0,0,1968,04,22
30,1968-05-24,Key West,United States,Anti-Castro Cubans,Explosives,0,0,1968,05,24

In [14]:
data_us['Total Injuries'] = data_us.groupby('Year')['Injuries'].transform(np.sum)
data_us['Total Fatalities'] = data_us.groupby('Year')['Fatalities'].transform(np.sum)

data_us.head()

/Users/catarinaneves/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/catarinaneves/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,Date,City,Country,Perpetrator,Weapon,Injuries,Fatalities,Year,Month,Day,Total Attacks,Total Injuries,Total Fatalities
4,1968-02-21,"Washington, D.C.",United States,Unknown,Explosives,0,0,1968,02,21,0,0,0
19,1968-03-19,Miami,United States,Anti-Castro Cubans,Explosives,0,0,1968,03,19,0,0,0
23,1968-04-22,New York City,United States,Anti-Castro Cubans,Explosives,0,0,1968,04,22,0,0,0
24,1968-04-22,New York City,United States,Anti-Castro Cubans,Explosives,0,0,1968,04,22,0,0,0
30,1968-05-24,Key West,United States,Anti-Castro Cubans,Explosives,0,0,1968,05,24,0,0,0

In [15]:
data_us = data_us.drop_duplicates(['Year'], keep = 'first')
data_us.head()

,Date,City,Country,Perpetrator,Weapon,Injuries,Fatalities,Year,Month,Day,Total Attacks,Total Injuries,Total Fatalities
4,1968-02-21,"Washington, D.C.",United States,Unknown,Explosives,0,0,1968,02,21,0,0,0
117,1969-06-08,New York City,United States,Anti-Castro Cubans,Explosives,0,0,1969,06,08,0,0,0
237,1970-04-24,New York City,United States,World United Formosans for Independence,Firearms,1,0,1970,04,24,4,4,0
380,1971-01-08,"Washington, D.C.",United States,Jewish Defense League (JDL),Explosives,0,0,1971,01,08,8,8,0
537,1972-01-22,New York City,United States,Unknown,Explosives,0,0,1972,01,22,1,1,0

In [19]:
trace0 = go.Scatter(
    x = data_us['Year'],
    y = data_us['Total Fatalities'],
    mode = 'lines',
    name = 'Fatalities',
    textfont=dict(size=7)
)

trace1 = go.Scatter(
    x = data_us['Year'],
    y = data_us['Total Injuries'],
    mode = 'lines',
    name = 'Injuries',
    textfont=dict(size=7)
)

layout = go.Layout(
    title ='Number of Injuries and Fatalities from Terror Attacks in US Soil by Year',
    titlefont = dict(size=12),
    showlegend=True,
    xaxis=dict(
        title= 'Year',
        titlefont=dict(size=0),
    ),
    yaxis=dict(
        title= '#',
        titlefont=dict(size=10),
    )
)

data = [trace0, trace1]
fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='Terror Attacks on US Soil')

2) # of Attacks in Turkish Soil by Year

In [40]:
data_tr = data[data['Country'] == 'Turkey']
data_tr.head()

,Date,City,Country,Perpetrator,Weapon,Injuries,Fatalities,Year,Month,Day
61,1968-08-10,Izmir,Turkey,Other,Fire or Firebomb,0,0,1968,08,10
196,1969-12-20,Ankara,Turkey,Unknown,Explosives,0,0,1969,12,20
200,1970-01-01,Istanbul,Turkey,Unknown,Explosives,0,0,1970,01,01
239,1970-04-25,Istanbul,Turkey,Unknown,Explosives,0,0,1970,04,25
241,1970-04-28,Ankara,Turkey,Unknown,Fire or Firebomb,0,0,1970,04,28

In [41]:
data_tr['Total Injuries'] = data_tr.groupby('Year')['Injuries'].transform(np.sum)
data_tr['Total Fatalities'] = data_tr.groupby('Year')['Fatalities'].transform(np.sum)

data_tr.head()

/Users/catarinaneves/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/catarinaneves/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,Date,City,Country,Perpetrator,Weapon,Injuries,Fatalities,Year,Month,Day,Total Injuries,Total Fatalities
61,1968-08-10,Izmir,Turkey,Other,Fire or Firebomb,0,0,1968,08,10,0,0
196,1969-12-20,Ankara,Turkey,Unknown,Explosives,0,0,1969,12,20,0,0
200,1970-01-01,Istanbul,Turkey,Unknown,Explosives,0,0,1970,01,01,2,0
239,1970-04-25,Istanbul,Turkey,Unknown,Explosives,0,0,1970,04,25,2,0
241,1970-04-28,Ankara,Turkey,Unknown,Fire or Firebomb,0,0,1970,04,28,2,0

In [42]:
data_tr = data_tr.drop_duplicates(['Year'], keep = 'first')
data_tr.head()

,Date,City,Country,Perpetrator,Weapon,Injuries,Fatalities,Year,Month,Day,Total Injuries,Total Fatalities
61,1968-08-10,Izmir,Turkey,Other,Fire or Firebomb,0,0,1968,08,10,0,0
196,1969-12-20,Ankara,Turkey,Unknown,Explosives,0,0,1969,12,20,0,0
200,1970-01-01,Istanbul,Turkey,Unknown,Explosives,0,0,1970,01,01,2,0
391,1971-01-23,Ankara,Turkey,Unknown,Explosives,0,0,1971,01,23,2,1
561,1972-03-27,NaN,Turkey,Turkish People's Liberation Army,Unknown,0,3,1972,03,27,0,3

In [43]:
trace0 = go.Scatter(
    x = data_tr['Year'],
    y = data_tr['Total Fatalities'],
    mode = 'lines',
    name = 'Fatalities',
    textfont=dict(size=7)
)

trace1 = go.Scatter(
    x = data_tr['Year'],
    y = data_tr['Total Injuries'],
    mode = 'lines',
    name = 'Injuries',
    textfont=dict(size=7)
)

layout = go.Layout(
    title ='Number of Injuries and Fatalities from Terror Attacks in Turkish Soil by Year',
    titlefont = dict(size=12),
    showlegend=True,
    xaxis=dict(
        title= 'Year',
        titlefont=dict(size=0),
    ),
    yaxis=dict(
        title= '#',
        titlefont=dict(size=10),
    )
)

data = [trace0, trace1]
fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='Terror Attacks on Turkish Soil')

Now looking by perpetrator...

In [44]:
data_tr_perp = data_tr.groupby(['Year', 'Perpetrator']).size().unstack(fill_value=0)

data_tr_perp.head()

Perpetrator,Abu Nidal Organization (ANO),Amal,Armenian Revolutionary Army,Black September,Dev Sol,Great Eastern Islamic Raiders Front (IBDA-C),Hizballah,Justice Commandos for the Armenian Genocide,Kurdish Workers Party,Kurdish Workers Party (PKK),Mahir Cayan Suicide Group,Other,People's Defense Forces (HPG),Turkish People's Liberation Army,Unknown
Year,,,,,,,,,,,,,,,
1968,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1969,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
1970,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
1971,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
1972,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

In [49]:
data_tr_perp['Year'] = data_tr_perp.index
data_tr_perp = data_tr_perp.reset_index(drop=True)
data_tr_perp.head()

Perpetrator,Abu Nidal Organization (ANO),Amal,Armenian Revolutionary Army,Black September,Dev Sol,Great Eastern Islamic Raiders Front (IBDA-C),Hizballah,Justice Commandos for the Armenian Genocide,Kurdish Workers Party,Kurdish Workers Party (PKK),Mahir Cayan Suicide Group,Other,People's Defense Forces (HPG),Turkish People's Liberation Army,Unknown,Year
0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1968
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1969
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1970
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1971
4,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1972

In [51]:
trace0 = go.Scatter(
    x = data_tr_perp['Year'],
    y = data_tr_perp['Abu Nidal Organization (ANO)'],
    mode = 'lines',
    name = 'Abu Nidal Organization (ANO)',
    textfont=dict(size=7)
)

trace1 = go.Scatter(
    x = data_tr_perp['Year'],
    y = data_tr_perp['Amal'],
    mode = 'lines',
    name = 'Amal',
    textfont=dict(size=7)
)

trace2 = go.Scatter(
    x = data_tr_perp['Year'],
    y = data_tr_perp['Armenian Revolutionary Army'],
    mode = 'lines',
    name = 'Armenian Revolutionary Army',
    textfont=dict(size=7)
)

trace3 = go.Scatter(
    x = data_tr_perp['Year'],
    y = data_tr_perp['Black September'],
    mode = 'lines',
    name = 'Black September',
    textfont=dict(size=7)
)

trace4 = go.Scatter(
    x = data_tr_perp['Year'],
    y = data_tr_perp['Dev Sol'],
    mode = 'lines',
    name = 'Dev Sol',
    textfont=dict(size=7)
)

trace5 = go.Scatter(
    x = data_tr_perp['Year'],
    y = data_tr_perp['Great Eastern Islamic Raiders Front (IBDA-C)'],
    mode = 'lines',
    name = 'Great Eastern Islamic Raiders Front (IBDA-C)',
    textfont=dict(size=7)
)

trace6 = go.Scatter(
    x = data_tr_perp['Year'],
    y = data_tr_perp['Hizballah'],
    mode = 'lines',
    name = 'Hizballah',
    textfont=dict(size=7)
)

trace7 = go.Scatter(
    x = data_tr_perp['Year'],
    y = data_tr_perp['Justice Commandos for the Armenian Genocide'],
    mode = 'lines',
    name = 'Justice Commandos for the Armenian Genocide',
    textfont=dict(size=7)
)

trace8 = go.Scatter(
    x = data_tr_perp['Year'],
    y = data_tr_perp['Kurdish Workers Party'],
    mode = 'lines',
    name = 'Kurdish Workers Party',
    textfont=dict(size=7)
)

trace9 = go.Scatter(
    x = data_tr_perp['Year'],
    y = data_tr_perp['Kurdish Workers Party (PKK)'],
    mode = 'lines',
    name = 'Kurdish Workers Party (PKK)',
    textfont=dict(size=7)
)

trace10 = go.Scatter(
    x = data_tr_perp['Year'],
    y = data_tr_perp['Mahir Cayan Suicide Group'],
    mode = 'lines',
    name = 'Mahir Cayan Suicide Group',
    textfont=dict(size=7)
)

trace11 = go.Scatter(
    x = data_tr_perp['Year'],
    y = data_tr_perp['Other'],
    mode = 'lines',
    name = 'Other',
    textfont=dict(size=7)
)


trace12 = go.Scatter(
    x = data_tr_perp['Year'],
    y = data_tr_perp['Unknown'],
    mode = 'lines',
    name = 'Unknown',
    textfont=dict(size=7)
)
                
layout = go.Layout(
    title ='Number of  Terror Attacks in Turkish Soil by Year and Perpetrator',
    titlefont = dict(size=12),
    showlegend=True,
    xaxis=dict(
        title= 'Year',
        titlefont=dict(size=0),
    ),
    yaxis=dict(
        title= '#',
        titlefont=dict(size=10),
    )
)

data = [trace0, trace1, trace2, trace3,trace4,trace5,trace6,trace7,trace8,trace9,trace10,trace11,trace12]
fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='Terror Attacks on Turkish Soil by Perp')